language: java
before_install:
  - echo "<settingsSecurity><master>$MAVEN_MASTER_PASSWORD</master></settingsSecurity>">$HOME/.m2/settings-security.xml
  - cp .travis.settings.xml $HOME/.m2/settings.xml
addons:
  sonarcloud:
    organization: "sftwnd-github"
    sourceEncoding: "UTF-8"
    projectKey: "sftwnd_crayfish"
    token:
      secure: "YOeJAOpFzl5uPQmoSXnxgMhB1JX/YBmOabfV+uBaeOwpUuhYa6NhFMf4bXyAI7j6NsMRv2J7KSXaW53afz3Nq//k78+NFG71ipALe7uMOQBsJ3xflAInSug5LgpRkDZcsWMkcDnC7lBYphFXnI7ULI2Utj9Ioe1MYIM8gtr9tDz0uW26BZD7BrLN8M1WLPSMzX9UDqVZ+7ZTEnZxhyTZbQEWu67cXpOLR+QN+P5SVnytthZFwGC38EeuVktRDNfaxuBeyiYqEWbbNvKWnGFKw4q7DmhqGhsStG+4UImVoqGyYoTjJcLrpQPzWNa7+qZHdkfRC4J6A5fkfURz9zDMbshDN+96I1rMoWLmF7ZJrwq/+cs7XAFW5o620t+a5jbVT/zfaitUnIqDI3R66p60+KA8zD9meCxQYrBYoN9R27v8ZJB6V18zRQbaTih44xlZdVNIolXsW3WSnfqsPoFDXsDS7xr4GXxbvQqFGedYNhjAcuCq5lxPvMbkv2/kENwvGSNEAsvmNpJefd2UlUMjzQ4V8T5ytBdkAgTAJrKbegbvqeV6qmniVk7CCeBJOPXSBYJ7UumXDUKnWJrzySW/P3piPO0Y3zjig3338vgIsN4k1iuwi2E8tA/2Pa66/ySCKbDR9T0FS2Hr/dxGXOiBBaTSb4FngFQlR7vSHgZg/V0="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sftwnd_crayfish
jdk: openjdk8
os: linux
